const char *__fastcall protocol_util_vbus_evt_to_str(int a1)
{
  char *v2; // [xsp+368h] [xbp-18h]

  switch ( a1 )
  {
    case 1:
      return "SET_BLE_EVT_CONNECT";
    case 2:
      return "SET_BLE_EVT_DISCONNECT";
    case 3:
      return "SYNC_EVT_ALRM_SYNC_COMPLETE";
    case 4:
      return "SYNC_EVT_CONFIG_SYNC_COMPLETE";
    case 5:
      return "SYNC_EVT_HEALTH_SYNC_COMPLETE";
    case 6:
      return "SYNC_EVT_HEALTH_PROGRESS";
    case 7:
      return "SYNC_EVT_ALARM_PROGRESS";
    case 8:
      return "SYNC_EVT_HEALTH_PROCESSING";
    case 9:
      return "SYNC_EVT_ALARM_PROCESSING";
    case 10:
      return "SYNC_EVT_CONFIG_PROCESSING";
    case 11:
      return "SYNC_EVT_CONFIG_FAST_SYNC_COMPLETE";
    case 12:
      return "SYNC_EVT_ACTIVITY_STOP_ONCE";
    case 13:
      return "SYNC_EVT_ACTIVITY_START_ONCE";
    case 15:
      return "SYNC_EVT_DATA_TRAN_PROCESSING";
    case 16:
      return "SYNC_EVT_DATA_TRAN_COMPLETE";
    case 18:
      return "SYNC_EVT_V3_HEALTH_COMPLETE";
    case 19:
      return "SYNC_EVT_V3_HEALTH_PROCESSING";
    case 20:
      return "SYNC_EVT_DATA_TRAN_PROCESSING_SPP";
    case 100:
      return "VBUS_EVT_APP_SET_ALARM";
    case 101:
      return "VBUS_EVT_APP_SET_LONG_SIT";
    case 102:
      return "VBUS_EVT_APP_SET_LOST_FIND";
    case 103:
      return "VBUS_EVT_APP_SET_FIND_PHONE";
    case 104:
      return "VBUS_EVT_APP_SET_TIME";
    case 105:
      return "VBUS_EVT_APP_SET_SPORT_GOAL";
    case 106:
      return "VBUS_EVT_APP_SET_SLEEP_GOAL";
    case 107:
      return "VBUS_EVT_APP_SET_USER_INFO";
    case 108:
      return "VBUS_EVT_APP_SET_UINT";
    case 109:
      return "VBUS_EVT_APP_SET_HAND";
    case 110:
      return "VBUS_EVT_APP_SET_APP_OS";
    case 111:
      return "VBUS_EVT_APP_SET_NOTICE";
    case 112:
      return "VBUS_EVT_APP_SET_HEART_RATE_INTERVAL";
    case 113:
      return "VBUS_EVT_APP_SET_HEART_RATE_MODE";
    case 114:
      return "VBUS_EVT_APP_SET_UP_HAND_GESTURE";
    case 115:
      return "VBUS_EVT_APP_SET_DEFAULT_CONFIG";
    case 116:
      return "VBUS_EVT_APP_SET_DO_NOT_DISTURB";
    case 117:
      return "VBUS_EVT_APP_SET_MUISC_ONOFF";
    case 118:
      return "VBUS_EVT_APP_SET_DISPLAY_MODE";
    case 119:
      return "VBUS_EVT_APP_SET_ONEKEY_SOS";
    case 120:
      return "VBUS_EVT_APP_SET_HR_SENSOR_PARAM";
    case 121:
      return "VBUS_EVT_APP_SET_GSENSOR_PARAM";
    case 122:
      return "VBUS_EVT_APP_SET_REAL_TIME_SENSOR_DATA";
    case 123:
      return "VBUS_EVT_APP_SET_START_MOTOT";
    case 124:
      return "VBUS_EVT_APP_SET_WATCH_DIAL";
    case 125:
      return "VBUS_EVT_APP_SET_SHORTCUT";
    case 126:
      return "VBUS_EVT_APP_SET_BP_CAL";
    case 127:
      return "VBUS_EVT_APP_SET_BP_MEASURE";
    case 128:
      return "VBUS_EVT_APP_SET_STRESS_CAL";
    case 150:
      return "VBUS_EVT_APP_SET_WEATHER_SWITCH";
    case 151:
      return "VBUS_EVT_APP_SET_SPORT_MODE_SELECT";
    case 152:
      return "VBUS_EVT_APP_SET_SLEEP_PERIOD";
    case 153:
      return "VBUS_EVT_APP_WEATCHER_DATA";
    case 154:
      return "VBUS_EVT_APP_SET_SCREEN_BRIGHTNESS";
    case 155:
      return "VBUS_EVT_APP_SET_CONFIG_GPS";
    case 156:
      return "VBUS_EVT_APP_SET_CONTROL_GPS";
    case 157:
      return "VBUS_EVT_APP_SET_CONN_PARAM";
    case 158:
      return "VBUS_EVT_APP_SET_HOT_START_PARAM";
    case 159:
      return "VBUS_EVT_APP_SET_MENSTRUATION";
    case 160:
      return "VBUS_EVT_APP_SET_MENSTRUATION_REMIND";
    case 161:
      return "VBUS_EVT_APP_SET_CALORIE_DISTANCE_GOAL";
    case 162:
      return "VBUS_EVT_APP_SET_SPO2";
    case 163:
      return "VBUS_EVT_APP_SET_PRESSURE";
    case 164:
      return "VBUS_EVT_APP_SET_SPORT_MODE_SORT";
    case 165:
      return "VBUS_EVT_APP_SET_WALK_REMINDER";
    case 166:
      return "VBUS_EVT_APP_SET_BREATHE_TRAIN";
    case 167:
      return "VBUS_EVT_APP_SET_ACTIVITY_SWITCH";
    case 168:
      return "VBUS_EVT_APP_SET_DRINK_WATER_REMINDER";
    case 169:
      return "VBUS_EVT_APP_SET_IOT_BUTTON_NAME";
    case 170:
      return "VBUS_EVT_APP_BLE_TO_APP_IOT_COMMAND";
    case 171:
      return "VBUS_EVT_APP_SET_MENU_LIST";
    case 194:
      return "VBUS_EVT_APP_SET_NOTICE_CALL_QUICK_REPLY_ON_OFF";
    case 195:
      return "VBUS_EVT_APP_SET_DRINK_WATER_PLAN";
    case 196:
      return "VBUS_EVT_APP_SET_ECG_REMINDER";
    case 197:
      return "VBUS_EVT_APP_SET_GAME_TIME_REMINDER";
    case 198:
      return "VBUS_EVT_APP_SET_STRIDE_DEVICE_SYNC";
    case 199:
      return "VBUS_EVT_APP_SET_DURING_EXERCISE";
    case 200:
      return "VBUS_EVT_APP_BIND_START";
    case 201:
      return "VBUS_EVT_APP_BIND_REMOVE";
    case 202:
      return "VBUS_EVT_APP_AUTH";
    case 203:
      return "VBUS_EVT_APP_BIND_REFUSE";
    case 204:
      return "VBUS_EVT_APP_SET_ENCRYPTED_AUTH";
    case 210:
      return "VBUS_EVT_APP_SET_FALL_MONITORING_SWITCH";
    case 300:
      return "VBUS_EVT_APP_APP_GET_MAC";
    case 301:
      return "VBUS_EVT_APP_GET_DEVICE_INFO";
    case 302:
      return "VBUS_EVT_APP_GET_FUNC_TABLE";
    case 303:
      return "VBUS_EVT_APP_GET_FUNC_TABLE_USER";
    case 304:
      return "VBUS_EVT_APP_GET_LIVE_DATA";
    case 306:
      return "VBUS_EVT_APP_GET_NOTICE_STATUS";
    case 309:
      return "VBUS_EVT_APP_GET_ACTIVITY_COUNT";
    case 310:
      return "VBUS_EVT_APP_GET_HID_INFO";
    case 311:
      return "VBUS_EVT_APP_GET_FUNC_TABLE_EX";
    case 312:
      return "VBUS_EVT_APP_GET_GPS_INFO";
    case 313:
      return "VBUS_EVT_APP_GET_HOT_START_PARAM";
    case 314:
      return "VBUS_EVT_APP_GET_GPS_STATUS";
    case 316:
      return "VBUS_EVT_APP_GET_DO_NOT_DISTURB";
    case 317:
      return "VBUS_EVT_APP_GET_MTU_INFO";
    case 319:
      return "VBUS_EVT_APP_GET_DOWN_LANGUAGE";
    case 320:
      return "VBUS_EVT_APP_GET_ERROR_RECORD";
    case 321:
      return "VBUS_EVT_APP_GET_BATT_INFO";
    case 322:
      return "VBUS_EVT_APP_GET_FLASH_BIN_INFO";
    case 342:
      return "VBUS_EVT_APP_GET_UNIT";
    case 343:
      return "VBUS_EVT_APP_GET_OTHER_SWITCH_STATE";
    case 344:
      return "VBUS_EVT_APP_GET_LEFT_RIGHT_WEAR_SETTINGS";
    case 345:
      return "VBUS_EVT_APP_GET_SETTINGS_DURING_EXERCISE";
    case 348:
      return "VBUS_EVT_APP_GET_FIRMWARE_STATUS_INFO";
    case 349:
      return "VBUS_EVT_APP_GET_FALL_MONITORING_SWITCH";
    case 350:
      return "VBUS_EVT_CHECK_REBOOT";
    case 351:
      return "VBUS_EVT_APP_GET_UNREAD_APP_ONOFF";
    case 352:
      return "VBUS_EVT_APP_GET_SET_BT_NOTICE";
    case 356:
      return "VBUS_EVT_APP_GET_DEVICE_CMEI";
    case 400:
      return "VBUS_EVT_APP_OTA_START";
    case 401:
      return "VBUS_EVT_APP_OTA_DIRECT_START";
    case 402:
      return "VBUS_EVT_APP_SYSTEM_OFF";
    case 403:
      return "VBUS_EVT_APP_REBOOT";
    case 405:
      return "VBUS_EVT_APP_CLEAN_BOND_INFO";
    case 406:
      return "VBUS_EVT_APP_SHUTDOWN";
    case 407:
      return "VBUS_EVT_APP_OTA_AUTH";
    case 410:
      return "VBUS_EVT_APP_SET_NOTICE_CALL";
    case 411:
      return "VBUS_EVT_APP_SET_NOTICE_MSG";
    case 412:
      return "VBUS_EVT_APP_SET_NOTICE_STOP_CALL";
    case 415:
      return "VBUS_EVT_APP_SET_NOTICE_CALL_TIME";
    case 420:
      return "VBUS_EVT_APP_SET_NOTICE_MISSED_CALL";
    case 500:
      return "VBUS_EVT_APP_APP_TO_BLE_MUSIC_START";
    case 501:
      return "VBUS_EVT_APP_APP_TO_BLE_MUSIC_STOP";
    case 502:
      return "VBUS_EVT_APP_APP_TO_BLE_PHOTO_START";
    case 503:
      return "VBUS_EVT_APP_APP_TO_BLE_PHOTO_STOP";
    case 504:
      return "VBUS_EVT_APP_APP_TO_BLE_FIND_DEVICE_START";
    case 505:
      return "VBUS_EVT_APP_APP_TO_BLE_FIND_DEVICE_STOP";
    case 506:
      return "VBUS_EVT_APP_APP_TO_BLE_OPEN_ANCS";
    case 511:
      return "VBUS_EVT_APP_APP_TO_BLE_NOTCIE_ICON_INFORMATIONG";
    case 513:
      return "VBUS_EVT_APP_APP_TO_BLE_NOTCIE_DISABLE_FUNC";
    case 514:
      return "VBUS_EVT_APP_APP_TO_BLE_NOTCIE_GET_PERIPHERAL_INFO_RESULT";
    case 565:
      return "VBUS_EVT_APP_BLE_TO_APP_VOLUME_PERCENTAGE";
    case 567:
      return "VBUS_EVT_APP_BLE_TO_APP_OPEN_APP_PHOTO_INTO_PREVIEW";
    case 568:
      return "VBUS_EVT_APP_BLE_TO_APP_PARSE_APP_PHOTO_STOP_PREVIEW";
    case 569:
      return "VBUS_EVT_APP_BLE_TO_APP_CLOSE_APP_PHOTO_OUT_PREVIEW";
    case 574:
      return "VBUS_EVT_APP_BLE_TO_APP_ONEKEY_SOS_START";
    case 575:
      return "VBUS_EVT_APP_BLE_TO_APP_SENSOR_DATA_NOTICE";
    case 576:
      return "VBUS_EVT_APP_BLE_TO_APP_DEVICE_OPERATE";
    case 581:
      return "VBUS_EVT_APP_BLE_TO_APP_DEVICE_PHOTOGRAPH";
    case 600:
      return "VBUS_EVT_APP_SWITCH_APP_STAERT";
    case 601:
      return "VBUS_EVT_APP_SWITCH_APP_START_REPLY";
    case 602:
      return "VBUS_EVT_APP_SWITCH_APP_ING";
    case 603:
      return "VBUS_EVT_APP_SWITCH_APP_ING_REPLY";
    case 604:
      return "VBUS_EVT_APP_SWITCH_APP_END";
    case 605:
      return "VBUS_EVT_APP_SWITCH_APP_END_REPLY";
    case 606:
      return "VBUS_EVT_APP_SWITCH_APP_PAUSE";
    case 607:
      return "VBUS_EVT_APP_SWITCH_APP_PAUSE_REPLY";
    case 608:
      return "VBUS_EVT_APP_SWITCH_APP_RESTORE";
    case 609:
      return "VBUS_EVT_APP_SWITCH_APP_RESTORE_REPLY";
    case 610:
      return "VBUS_EVT_APP_SWITCH_APP_BLE_PAUSE";
    case 611:
      return "VBUS_EVT_APP_SWITCH_APP_BLE_PAUSE_REPLY";
    case 612:
      return "VBUS_EVT_APP_SWITCH_APP_BLE_RESTORE";
    case 613:
      return "VBUS_EVT_APP_SWITCH_APP_BLE_RESTORE_REPLY";
    case 614:
      return "VBUS_EVT_APP_SWITCH_APP_BLE_END";
    case 615:
      return "VBUS_EVT_APP_SWITCH_APP_BLE_END_REPLY";
    case 618:
      return "VBUS_EVT_APP_SWITCH_APP_GET_HR_INTERVAL";
    case 620:
      return "VBUS_EVT_APP_SWITCH_BLE_START";
    case 621:
      return "VBUS_EVT_APP_SWITCH_BLE_START_REPLY";
    case 622:
      return "VBUS_EVT_APP_SWITCH_BLE_ING";
    case 623:
      return "VBUS_EVT_APP_SWITCH_BLE_ING_REPLY";
    case 624:
      return "VBUS_EVT_APP_SWITCH_BLE_END";
    case 625:
      return "VBUS_EVT_APP_SWITCH_BLE_END_REPLY";
    case 626:
      return "VBUS_EVT_APP_SWITCH_BLE_PAUSE";
    case 627:
      return "VBUS_EVT_APP_SWITCH_BLE_PAUSE_REPLY";
    case 628:
      return "VBUS_EVT_APP_SWITCH_BLE_RESTORE";
    case 629:
      return "VBUS_EVT_APP_SWITCH_BLE_RESTORE_REPLY";
    case 650:
      return "VBUS_EVT_APP_ACTIVITY_SYNC_TIMEOUT";
    case 651:
      return "VBUS_EVT_APP_ACTIVITY_SYNC_COMPLETE";
    case 652:
      return "VBUS_EVT_APP_ACTIVITY_SYNC_ONCE_COMPLETE_JSON_NOTEICE";
    case 653:
      return "VBUS_EVT_APP_GPS_SYNC_COMPLETE";
    case 900:
      return "VBUS_EVT_APP_PROTOCOL_TEST_CMD_1";
    case 1000:
      return "VBUS_EVT_IBEACON_WRITE_HEAD";
    case 1001:
      return "VBUS_EVT_IBEACON_WRITE_HEAD_REPLY";
    case 1002:
      return "VBUS_EVT_IBEACON_WRITE_UUID";
    case 1003:
      return "VBUS_EVT_IBEACON_WRITE_UUID_REPLY";
    case 1004:
      return "VBUS_EVT_IBEACON_WRITE_PASSWORD";
    case 1005:
      return "VBUS_EVT_IBEACON_WRITE_PASSWORD_REPLY";
    case 1006:
      return "VBUS_EVT_IBEACON_GET_HEAD";
    case 1007:
      return "VBUS_EVT_IBEACON_GET_HEAD_REPY";
    case 1008:
      return "VBUS_EVT_IBEACON_GET_UUID";
    case 1009:
      return "VBUS_EVT_IBEACON_GET_UUID_REPLY";
    case 5000:
      return "VBUS_EVT_FUNC_ADD_ALARM";
    case 5002:
      return "VBUS_EVT_FUNC_START_SYNC_V3_HEALTH";
    case 5003:
      return "VBUS_EVT_FUNC_STOP_SYNC_V3_HEALTH";
    case 5004:
      return "VBUS_EVT_FUNC_GET_ANCS_APPID";
    case 5005:
      return "VBUS_EVT_FUNC_SET_ANCS_PARAM";
    case 5010:
      return "VBUS_EVT_FUNC_V3_SET_HR_MODE";
    case 5013:
      return "VBUS_EVT_FUNC_V3_SPORT_SORT";
    case 5016:
      return "VBUS_EVT_FUNC_V3_GET_SPORT_TYPE";
    case 5017:
      return "VBUS_EVT_FUNC_V3_SPORT_SORT";
    case 5018:
      return "VBUS_EVT_FUNC_V3_GET_ALARM";
    case 5019:
      return "VBUS_EVT_FUNC_V3_GET_HEAT_LOG";
    case 5020:
      return "VBUS_EVT_FUNC_V3_SET_FAST_MSG";
    case 5021:
      return "VBUS_EVT_FUNC_V3_ACTIVITY_DATA_EXCHANGE";
    case 5031:
      return "VBUS_EVT_FUNC_V3_GET_V3_FUNCTION_TABLE";
    case 5060:
      return "VBUS_EVT_FUNC_V3_GET_ALGORITHM_VERSION";
    case 5500:
      return "VBUS_EVT_FUNC_MAKE_PHOTO";
    case 5510:
      return "VBUS_EVT_FUNC_SIMPLE_FILE_OPERATIONS";
    case 5511:
      return "VBUS_EVT_FUNC_FLASH_LOG_START";
    case 5512:
      return "VBUS_EVT_FUNC_FLASH_LOG_STOP";
    case 5513:
      return "VBUS_EVT_FUNC_FLASH_LOG_COMPLETE";
    case 6000:
      return "VBUS_EVT_TRAN_JSON_HEALTH_SPORT";
    case 6001:
      return "VBUS_EVT_TRAN_JSON_HEALTH_SLEEP";
    case 6002:
      return "VBUS_EVT_TRAN_JSON_HEALTH_HR";
    case 6003:
      return "VBUS_EVT_TRAN_JSON_HEALTH_BP";
    case 6004:
      return "VBUS_EVT_TRAN_JOSN_GPS";
    case 6500:
      return "VBUS_EVT_APP_WEATCHER_CITY_NAME";
    case 6501:
      return "VBUS_EVT_APP_WEATCHER_REAL_TIME_ONE";
    case 6502:
      return "VBUS_EVT_APP_WEATCHER_REAL_TIME_TWO";
    case 6503:
      return "VBUS_EVT_APP_WEATCHER_REAL_TIME_THREE";
    case 7625:
      return "VBUS_EVT_VOICE_SET_ON_OFF_FUNCTION";
    case 7633:
      return "VBUS_EVT_VOICE_TRAN_TO_BLE_START";
    case 7634:
      return "VBUS_EVT_VOICE_TRAN_TO_BLE_ON_GOING";
    case 7635:
      return "VBUS_EVT_VOICE_TRAN_TO_BLE_END";
    case 7951:
      return "VBUS_EVT_APP_GET_MTU_LENGTH_SPP";
  }
  v2 = byte_101E3D9;
  snprintf(byte_101E3D9, 0x64uLL, "%d", a1);
  return v2;
}